"""Life Hub services — all providers.

Strategy:
- Generic handlers (simply call client.{method} with ServiceCall.data as kwargs)
  are generated by ``_make_handler()`` to eliminate fliggy/baidu/tongcheng boilerplate.
- Providers with special dispatch logic (yiming, meituan) or result-wrapping (gaode)
  keep hand-written closures.
- Registration is a single declarative list at the bottom, not 350 lines.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

import voluptuous as vol
from homeassistant.core import HomeAssistant, ServiceCall, SupportsResponse
from homeassistant.exceptions import HomeAssistantError

_LOGGER = logging.getLogger(__name__)

from .const import DOMAIN


# ═══════════════════════════════════════════════════════════
# Infrastructure
# ═══════════════════════════════════════════════════════════

_current_hass: HomeAssistant | None = None


def _get_provider_client(hass: HomeAssistant, provider_type: str):
    """Get client for a specific provider type via O(1) lookup."""
    client_map = hass.data.get(DOMAIN, {}).get("client_map", {})
    for key, (client, rt) in client_map.items():
        if key.startswith(f"{provider_type}:"):
            return client, rt
    # Fallback: iterate entries (safe for edge cases)
    for entry in hass.config_entries.async_entries(DOMAIN):
        runtime = getattr(entry, "runtime_data", None)
        if runtime is None:
            continue
        for key, rt in runtime.providers.items():
            if key.startswith(f"{provider_type}:") and hasattr(rt, "client"):
                return rt.client, rt
    raise HomeAssistantError(f"未找到 {provider_type} 集成")


def _make_handler(provider: str, method: str):
    """Factory: create a handler that calls ``client.{method}(**call.data)``."""
    async def handler(call: ServiceCall) -> Any:
        client, _ = _get_provider_client(_current_hass, provider)
        try:
            result = await getattr(client, method)(**dict(call.data))
            return result or {}
        except TypeError as err:
            _LOGGER.warning("_make_handler %s.%s failed: %s", provider, method, err)
            raise HomeAssistantError(f"Provider {provider} method {method} failed: {err}") from err
    return handler


def _make_dispatch_handler(provider: str):
    """Factory: create a handler that dispatches ``client.{method}(**params)``.

    Expected service call data: ``{"method": "...", "params": {...}}``.
    """
    async def handler(call: ServiceCall) -> Any:
        client, _ = _get_provider_client(_current_hass, provider)
        method = call.data["method"]
        params = call.data.get("params", {})
        try:
            fn = getattr(client, method)
            result = await fn(**params)
            return result or {}
        except TypeError as err:
            _LOGGER.warning("_make_dispatch_handler %s.%s failed: %s", provider, method, err)
            raise HomeAssistantError(f"Provider {provider} method {method} failed: {err}") from err
    return handler


# ═══════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════

def _parse_json_list(raw: str | list) -> list:
    """Parse a JSON string or return list as-is."""
    return json.loads(raw) if isinstance(raw, str) else raw


def _get_lng_lat(hass: HomeAssistant) -> tuple[float, float]:
    """Get location from HA config, returns (lng, lat) or (0, 0)."""
    lat = hass.config.latitude
    lng = hass.config.longitude
    if lat and lng:
        return float(lng), float(lat)
    return 0.0, 0.0


async def _get_location(hass: HomeAssistant) -> tuple[float, float] | None:
    """Get location from HA config."""
    lat = hass.config.latitude
    lng = hass.config.longitude
    if lat and lng:
        return float(lng), float(lat)
    return None


# ═══════════════════════════════════════════════════════════
# Hand-written closures (dispatch dicts / result-wrapping)
# ═══════════════════════════════════════════════════════════

async def _handle_yiming(call: ServiceCall) -> Any:
    """Dispatch yiming API calls via method+params."""
    method = call.data["method"]

    # Special: claim_all iterates over all yiming accounts
    if method == "claim_all":
        results = {}
        client_map = _current_hass.data.get(DOMAIN, {}).get("client_map", {})
        for key, (client, rt) in client_map.items():
            if not key.startswith("yiming:"):
                continue
            try:
                result = await client.receive_all_coupons()
                results[key] = {"status": "ok", "result": result.get("msg", "ok")}
            except Exception as err:
                results[key] = {"status": "error", "error": str(err)}
        return results

    client, _ = _get_provider_client(_current_hass, "yiming")
    params = call.data.get("params", {})

    def _lat():
        return _get_lng_lat(_current_hass)

    _DISPATCH = {
        # 查询类
        "get_balance": lambda: client.get_balance(),
        "get_member_info": lambda: client.get_member_info(),
        "get_coupon_sum": lambda: client.get_coupon_sum(),
        "get_integral": lambda: client.get_integral(),
        "get_user_info": lambda: client.get_user_info(),
        "get_app_notice": lambda: client.get_app_notice(),
        "get_coupon_pools": lambda: client.get_coupon_pools(),
        "get_orders": lambda: client.get_orders(params.get("page_num", 1), params.get("page_size", 5)),
        "get_my_coupons": lambda: client.get_my_coupons(params.get("page_num", 1), params.get("page_size", 20), params.get("usable", 1)),
        "get_integral_detail": lambda: client.get_integral_detail(params.get("page_num", 1), params.get("page_size", 5)),
        "get_recharge_list": lambda: client.get_recharge_list(),
        "get_app_equity": lambda: client.get_app_equity(),
        "get_user_info_v2": lambda: client.get_user_info_v2(),
        "get_qrcode": lambda: client.get_qrcode(),
        "get_order": lambda: client.get_order(params["order_no"]),
        "get_transaction_details": lambda: client.get_transaction_details(),
        "get_default_address": lambda: client.get_default_address(),
        # 门店/位置
        "get_nearest_store": lambda: client.query_nearest_enable_store(*_lat()),
        "get_menu": lambda: client.get_goods_category(params.get("shop_code", ""), *_lat()),
        "get_sku_info": lambda: client.get_sku_info(params["goods_id"], params["shop_code"]),
        "search_stores": lambda: client.query_store_list_by_page(*_lat(), params.get("city", ""), params.get("keyword", "")),
        "get_delivery_time": lambda: client.get_delivery_time(params["store_code"], params.get("order_type", "3")),
        "get_nearby_addresses": lambda: client.get_personal_nearly_address_list(*_lat()),
        "get_store_info": lambda: client.get_store_info(params["store_code"]),
        "get_region_list": lambda: client.get_region_list(params.get("user_city", "")),
        "get_current_city": lambda: client.get_current_city(*_lat()),
        "query_nearly_store": lambda: client.query_nearly_store(*_lat(), params.get("city", "")),
        "query_nearly_store_by_distance": lambda: client.query_nearly_store_by_distance(*_lat(), params.get("distance", 3000)),
        "get_nearly_store_one_km": lambda: client.get_nearly_store_one_km(*_lat()),
        # 下单/购物车
        "calculate_cart": lambda: client.shopping_cart_calculation(_parse_json_list(params.get("goods_list", "[]"))),
        "pre_create_order": lambda: client.pre_create_order(params.get("shop_code", ""), _parse_json_list(params.get("goods_list", "[]"))),
        "submit_order": lambda: client.submit_order(
            shop_code=params.get("shop_code", ""),
            shop_name=params.get("shop_name", ""),
            goods_list=_parse_json_list(params.get("goods_list", "[]")),
            order_type=params.get("order_type", "1"),
            pay_type=params.get("pay_type", 1),
            mobile=params.get("mobile", ""),
            remark=params.get("remark", ""),
            longitude=params.get("longitude"), latitude=params.get("latitude"),
        ),
        # 优惠券
        "receive_all_coupons": lambda: client.receive_all_coupons(),
        "receive_coupon": lambda: client.receive_coupon(params["equity_pool_id"], params["coupon_code"], params.get("receive_num", 1)),
        # 收藏
        "collect_store_query": lambda: client.collect_store_query(*_lat(), params.get("city", "")),
        "collect_store_create": lambda: client.collect_store_create(params["store_id"]),
    }
    fn = _DISPATCH.get(method)
    if fn is None:
        raise HomeAssistantError(f"未知的一鸣 API 方法: {method}")
    return await fn()


async def _handle_meituan(call: ServiceCall) -> dict:
    """Dispatch meituan API calls via method+params."""
    client, _ = _get_provider_client(_current_hass, "meituan")
    return await client.call_method(call.data["method"], call.data.get("params", {})) or {}


async def _handle_mcdonalds(call: ServiceCall) -> dict:
    """McDonald's MCP call_tool with JSON string support."""
    client, _ = _get_provider_client(_current_hass, "mcdonalds")
    args_raw = call.data.get("arguments", "{}")
    args = json.loads(args_raw) if isinstance(args_raw, str) else args_raw
    return await client.call_tool(call.data["tool_name"], args) or {}


# ═══════════════════════════════════════════════════════════
# Declarative registration
# ═══════════════════════════════════════════════════════════

@dataclass
class _Svc:
    name: str
    handler: Callable
    schema: vol.Schema


_SERVICES: list[_Svc] = [
    # ── Yiming ──
    _Svc("yiming_call_api", _handle_yiming, vol.Schema({
        vol.Required("method"): vol.In([
            "get_balance", "get_member_info", "get_coupon_sum", "get_integral",
            "get_user_info", "get_app_notice", "get_coupon_pools", "get_orders",
            "get_my_coupons", "get_integral_detail", "get_recharge_list",
            "get_app_equity", "get_user_info_v2", "get_qrcode", "get_order",
            "get_transaction_details", "get_default_address",
            "get_nearest_store", "get_menu", "get_sku_info", "search_stores",
            "get_delivery_time", "get_nearby_addresses", "get_store_info",
            "get_region_list", "get_current_city", "query_nearly_store",
            "query_nearly_store_by_distance", "get_nearly_store_one_km",
            "calculate_cart", "pre_create_order", "submit_order",
            "receive_all_coupons", "receive_coupon", "claim_all",
            "collect_store_query", "collect_store_create",
        ]),
        vol.Optional("params", default={}): dict,
    })),
    # ── Fliggy ──
    _Svc("fliggy_call_api", _make_dispatch_handler("fliggy"), vol.Schema({
        vol.Required("method"): vol.In([
            "fast_search", "ai_search", "search_flight", "search_hotel",
            "search_train", "search_poi",
            "search_marriott_hotel", "search_marriott_package",
        ]),
        vol.Optional("params", default={}): dict,
    })),
    # ── Ctrip ──
    _Svc("ctrip_call_api", _make_dispatch_handler("ctrip"), vol.Schema({
        vol.Required("method"): vol.In(["query", "search_hotel"]),
        vol.Optional("params", default={}): dict,
    })),
    # ── McDonald's ──
    _Svc("mcdonalds_call_tool", _handle_mcdonalds, vol.Schema({
        vol.Required("tool_name"): str,
        vol.Optional("arguments", default="{}"): vol.Any(str, dict),
    })),
    # ── Baidu Maps ──
    _Svc("baidu_map_call_api", _make_dispatch_handler("baidu_map"), vol.Schema({
        vol.Required("method"): vol.In(["search_poi", "geocode", "reverse_geocode"]),
        vol.Optional("params", default={}): dict,
    })),
    # ── Meituan ──
    _Svc("meituan_call_api", _handle_meituan, vol.Schema({
        vol.Required("method"): str,
        vol.Optional("params", default={}): dict,
    })),
    # ── Meituan Travel ──
    _Svc("meituan_travel_call_api", _make_dispatch_handler("meituan_travel"), vol.Schema({
        vol.Required("method"): vol.In([
            "search_hotel", "search_flight", "search_train", "search_poi",
            "plan_itinerary", "get_travel_orders",
        ]),
        vol.Optional("params", default={}): dict,
    })),
    # ── Gaode ──
    _Svc("gaode_call_api", _make_dispatch_handler("gaode"), vol.Schema({
        vol.Required("method"): vol.In([
            "search_poi", "search_poi_nearby", "geocode", "reverse_geocode",
            "get_distance", "calculate_distance", "check_in_polygon",
        ]),
        vol.Optional("params", default={}): dict,
    })),
    # ── Music ──
    _Svc("music_call_api", _make_dispatch_handler("music"), vol.Schema({
        vol.Required("method"): vol.In(["search_songs", "get_playlist", "get_ranking"]),
        vol.Optional("params", default={}): dict,
    })),
    # ── Didi ──
    _Svc("didi_call_tool", _make_handler("didi", "call_tool"), vol.Schema({
        vol.Required("tool_name"): vol.In([
            "taxi_estimate", "taxi_create_order", "taxi_query_order",
            "taxi_cancel_order", "taxi_get_driver_location", "taxi_generate_ride_app_link",
            "maps_textsearch", "maps_place_around", "maps_regeocode",
            "maps_direction_driving", "maps_direction_transit",
            "maps_direction_walking", "maps_direction_bicycling",
        ]),
        vol.Optional("arguments", default={}): dict,
    })),
]


async def async_setup_services(hass: HomeAssistant) -> None:
    """Register all life_hub services."""
    global _current_hass
    _current_hass = hass

    for svc in _SERVICES:
        if not hass.services.has_service(DOMAIN, svc.name):
            hass.services.async_register(
                DOMAIN, svc.name, svc.handler, schema=svc.schema,
                supports_response=SupportsResponse.OPTIONAL,
            )
        else:
            _LOGGER.debug("Service %s already registered, skipping", svc.name)
